### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [juhp/sourcemap#1]
```
sourcemap                      > /tmp/stack-d9418d8d13cbf63c/sourcemap-0.1.6.1/src/SourceMap.hs:33:38: error:
sourcemap                      >     • Couldn't match type: Map.HashMap k0 Value
sourcemap                      >                      with: Data.Aeson.KeyMap.KeyMap Value
sourcemap                      >       Expected: Object
sourcemap                      >         Actual: Map.HashMap k0 Value
sourcemap                      >     • In the first argument of ‘Object’, namely ‘(Map.fromList obj)’
sourcemap                      >       In the expression: Object (Map.fromList obj)
sourcemap                      >       In an equation for ‘generate’:
sourcemap                      >           generate SourceMapping {..}
sourcemap                      >             = Object (Map.fromList obj)
sourcemap                      >             where
sourcemap                      >                 obj
sourcemap                      >                   = [("version", toJSON version), ....]
sourcemap                      >                       ++ [("sourceRoot", toJSON root) | Just root <- [...]]
sourcemap                      >                 names = nub $ mapMaybe mapName smMappings
sourcemap                      >                 sources = symbols mapSourceFile
sourcemap                      >                 symbols f = sort (nub (mapMaybe f smMappings))
sourcemap                      >     • Relevant bindings include
sourcemap                      >         obj :: [(k0, Value)] (bound at src/SourceMap.hs:34:3)
sourcemap                      >    |
sourcemap                      > 33 | generate SourceMapping{..} = Object (Map.fromList obj) where
sourcemap                      >    |                                      ^^^^^^^^^^^^^^^^
```
